const MODULES=["Fundamentos","Vistas Ortogonales","Proyecciones","Secciones y Cortes","Perspectiva","Desarrollo de Cuerpos","Gemelo Geométrico 2D–3D","Ejercicios","Evaluación","Progreso","Asistente IA local"];
const NAVICONS=['ruler','panels-top-left','scan-line','slice','box','unfold-horizontal','workflow','pencil-ruler','clipboard-check','chart-no-axes-combined','messages-square'];
const PIECES=["Cubo","Prisma","Cilindro","Esfera","Cono","Pirámide","Escalonada","Soporte","Angular","Brida","Eje","Bloque perforado","Carcasa","Cavidades","Inclinada","Soporte mecánico","Perforaciones múltiples","Combinada"];
const PIECE_INFO={"Cubo":["Poliedro regular","Seis caras cuadradas: relaciona dimensiones iguales en los tres planos.","□"],"Prisma":["Prisma rectangular","Seis caras rectangulares: distingue anchura, altura y profundidad.","▣"],"Cilindro":["Superficie de revolución","Cilindro facetado: compara bases circulares y generatrices laterales.","◯"],"Esfera":["Superficie de revolución","Esfera facetada: estudia siluetas circulares y normales variables; cada cara es seleccionable.","◉"],"Cono":["Superficie de revolución","Cono facetado con vértice común: relaciona base, generatrices y alzado triangular.","△"],"Pirámide":["Poliedro de base cuadrada","Base cuadrada y cuatro caras triangulares: sigue caras oblicuas entre planos.","◇"],"Escalonada":["Prisma cóncavo escalonado","Perfil extruido en L: identifica entrantes y cambios de altura.","▤"],"Soporte":["Perfil angular extruido","Equivalente didáctico de soporte en L, sin ensamblajes: interpreta alas y concavidad.","⌜"],"Angular":["Perfil angular extruido","Compara espesores y aristas ocultas del perfil en L.","∟"],"Brida":["Marco prismático perforado","Bloque didáctico con un taladro rectangular: sigue el contorno interior.","▣"],"Eje":["Cilindro recto facetado","Cilindro sin escalones ni chaveteros. Reconoce el eje de revolución.","◎"],"Bloque perforado":["Prisma con abertura pasante","Un hueco rectangular atraviesa el bloque: distingue caras interiores y exteriores.","▧"],"Carcasa":["Bloque mecánico escalonado","Base rectangular y cuerpo posterior elevado: interpreta plataformas y perfil escalonado.","▥"],"Cavidades":["Bloque escalonado con rebaje central","Pocket rectangular superior abierto con fondo y paredes interiores reales.","▦"],"Inclinada":["Bloque escalonado con rampa","Base y cuerpo posterior unidos por una rampa plana real.","◢"],"Soporte mecánico":["Soporte angular L perforado","Placas vertical y base con taladros circulares pasantes y paredes interiores facetadas.","⌞"],"Perforaciones múltiples":["Soporte L con cinco taladros","Tres taladros en vertical y dos en base; las cinco perforaciones atraviesan el espesor.","⌗"],"Combinada":["Soporte L perforado con cartelas","Taladros pasantes y dos cartelas triangulares laterales como volúmenes reales.","⌑"]};
const QUESTIONS=[
{module:"Vistas Ortogonales",question:"¿Qué dimensiones conserva la vista frontal de la pieza?",options:["Anchura y altura","Anchura y profundidad","Altura y profundidad"],answer:0,why:"El alzado proyecta sobre XY: conserva anchura y altura; la profundidad queda perpendicular al plano.",hint:"Observa los ejes X e Y del alzado."},
{module:"Fundamentos",question:"¿Cómo se representa una arista que queda detrás de una superficie?",options:["Línea continua gruesa","Línea discontinua fina","Línea de trazo y punto"],answer:1,why:"Las aristas ocultas se dibujan con trazos discontinuos finos. Trazo y punto se reserva para ejes.",hint:"Una línea visible no puede confundirse con una oculta."},
{module:"Vistas Ortogonales",question:"Una anchura real de 80 mm a escala 1:2 ocupa en el papel…",options:["160 mm","80 mm","40 mm"],answer:2,why:"1:2 reduce a la mitad: 80 / 2 = 40 mm. La cifra de cota sigue indicando 80 mm reales.",hint:"Divide la dimensión real por el denominador de la escala."},
{module:"Secciones y Cortes",question:"Un plano horizontal atraviesa un cilindro vertical. ¿Qué sección produce?",options:["Triángulo","Círculo","Rectángulo"],answer:1,why:"Todo plano perpendicular al eje de un cilindro circular recto produce un círculo del mismo radio.",hint:"El plano es perpendicular al eje del cilindro."},
{module:"Perspectiva",question:"En perspectiva de dos puntos, las horizontales de dos direcciones…",options:["Convergen a dos puntos del horizonte","Convergen todas al centro","Son siempre paralelas"],answer:0,why:"Cada familia de paralelas horizontales converge a su propio punto de fuga, ambos sobre el horizonte.",hint:"Cada dirección espacial tiene un punto de fuga."},
{module:"Desarrollo de Cuerpos",question:"El ancho del rectángulo lateral de un cilindro de radio r es…",options:["πr²","2r","2πr"],answer:2,why:"Al abrir la superficie lateral, la circunferencia se convierte en el ancho del rectángulo: 2πr.",hint:"El borde del rectángulo rodeaba la base completa."}];
const STEPS=["Objeto: observa sus tres dimensiones antes de dibujarlo.","Caras: identifica qué superficies miran al observador.","Plano: un plano receptor se sitúa detrás del objeto.","Rayos: las proyectantes paralelas unen vértices y plano.","Proyección: cada punto 3D tiene una posición sobre el dibujo.","Interpretación: distingue contornos, ocultas y dimensiones."];
const defaults={module:'Vistas Ortogonales',piece:'Escalonada',level:'3',view:'Isométrica',projection:'Ortogonal',camera:'Ortográfica',render_mode:'Sólido + aristas',color:'#718e96',light:'2.5',flags:{Visibles:true,Ocultas:true,Ejes:false,Centros:false,Cotas:true,Superficies:true,Proyectantes:false,'Aristas 3D':true},cut:'0',cut_type:'Completa',hatch_angle:'45',hatch_gap:'8',hatch_style:'Simple',perspective:'Dos puntos',distance:'260',height:'40',orientation:'30',body:'Prisma',unfold:0,explaining:false,step:0};
let S={...defaults,flags:{...defaults.flags},playing:false,unfolding:false,exercise:0,answer:-1,checked:false,hint_count:0,attempts:0,score:0,solved:[],exam_answers:[-1,-1,-1,-1,-1],exam_index:0,exam_finished:false,visited:['Vistas Ortogonales'],recent:[],messages:[{role:'assistant',text:'Soy tu asistente pedagógico local. Selecciona una arista o pregúntame cómo interpretar la pieza. Trabajo con reglas educativas, sin servicios externos de IA.'}]};
function load(){try{const x=JSON.parse(localStorage.getItem('cadLabState'));if(x)S={...S,...x,flags:{...S.flags,...(x.flags||{})}}}catch(e){}}
function save(){localStorage.setItem('cadLabState',JSON.stringify(S))}
function sync(){window.cadConfig={module:S.module,piece:S.piece,view:S.view,projection:S.projection,camera:S.camera,render_mode:S.render_mode,color:S.color,light:S.light,flags:S.flags,cut:S.cut,cut_type:S.cut_type,hatch_angle:S.hatch_angle,hatch_gap:S.hatch_gap,hatch_style:S.hatch_style,perspective:S.perspective,distance:S.distance,height:S.height,orientation:S.orientation,body:S.body,unfold:S.unfold,explaining:S.explaining,step:S.step}}
function icon(n){return `<i data-lucide="${n}"></i>`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pieces(){return PIECES.slice((+S.level-1)*3,(+S.level-1)*3+3)}
function desc(){return ({'Fundamentos':'El lenguaje gráfico con el que se construye una idea.','Vistas Ortogonales':'Un objeto, tres miradas. Aprende a leer el espacio en dos dimensiones.','Proyecciones':'Explora cómo la dirección de los rayos transforma el dibujo.','Secciones y Cortes':'Abre la pieza con un plano y descubre su geometría interior.','Perspectiva':'Del espacio al papel: paralelas, horizonte y puntos de fuga.','Desarrollo de Cuerpos':'Despliega superficies y relaciona el sólido con su plantilla.','Gemelo Geométrico 2D–3D':'Selecciona una arista. Encuentra la misma geometría en ambas representaciones.','Ejercicios':'Observa, razona y comprueba. Las pistas te acompañan.','Evaluación':'Cinco preguntas para poner a prueba tu lectura del espacio.','Progreso':'Tu recorrido de aprendizaje en esta sesión, sin datos inventados.','Asistente IA local':'Orientación pedagógica por reglas, vinculada a tu estación de trabajo.'})[S.module]||''}
function setCfg(k,v){if(k==='level'){S.level=v;S.piece=pieces()[0]||PIECES[0]}else S[k]=v;save();sync();render();if(k==='view'&&window.cadReset)window.cadReset()}
function navigate(m){S.module=m;if(!S.visited.includes(m))S.visited.push(m);save();sync();render()}
function toggle(k){S.flags[k]=!S.flags[k];save();sync();render()}
function resetView(){if(window.cadReset)window.cadReset();S.view='Isométrica';save();sync();render()}
function explain(){S.explaining=!S.explaining;if(S.explaining)S.step=0;save();sync();render()}
function step(d){S.step=Math.max(0,Math.min(5,S.step+d));save();sync();render()}
function playExplain(){S.playing=!S.playing;if(S.playing){clearInterval(window.expTimer);window.expTimer=setInterval(()=>{if(!S.playing){clearInterval(window.expTimer);return}S.step++;if(S.step>=5){S.step=5;S.playing=false}sync();render()},2500)}render()}
function playUnfold(){S.unfolding=!S.unfolding;if(S.unfolding){if(+S.unfold>=100)S.unfold=0;clearInterval(window.unfoldTimer);window.unfoldTimer=setInterval(()=>{if(!S.unfolding){clearInterval(window.unfoldTimer);return}S.unfold=Math.min(100,+S.unfold+2);if(S.unfold===100)S.unfolding=false;sync();render()},80)}render()}
function resetUnfold(){S.unfold=0;S.unfolding=false;save();sync();render()}
function answer(i){S.answer=i;S.checked=false;render()}
function check(){if(S.answer<0||S.checked)return;const q=QUESTIONS[S.exercise];S.checked=true;S.attempts++;if(S.answer===q.answer&&!S.solved.includes(S.exercise)){S.solved.push(S.exercise);S.score++}S.recent.unshift(`Ejercicio ${S.exercise+1}: ${S.answer===q.answer?'correcto':'revisar respuesta'}`);S.recent=S.recent.slice(0,8);save();render()}
function hint(){const q=QUESTIONS[S.exercise];if(S.hint_count<2)S.hint_count++;save();render()}
function nextEx(){S.exercise=(S.exercise+1)%QUESTIONS.length;S.answer=-1;S.checked=false;S.hint_count=0;save();render()}
function examNext(){const q=QUESTIONS[[1,2,3,4,5][S.exam_index]];if(S.exam_answers[S.exam_index]<0)return;if(S.exam_index===4)S.exam_finished=true;else S.exam_index++;save();render()}
function examAnswer(i){S.exam_answers[S.exam_index]=i;render()}
function examScore(){return S.exam_answers.reduce((n,a,i)=>n+(a===QUESTIONS[[1,2,3,4,5][i]].answer?1:0),0)}
function restartExam(){S.exam_answers=[-1,-1,-1,-1,-1];S.exam_index=0;S.exam_finished=false;save();render()}
function resetSession(){localStorage.removeItem('cadLabState');location.reload()}
function reply(text){text=(text||'').trim();if(!text)return;S.messages.push({role:'user',text});let r='Puedo ayudarte a interpretar vistas, cotas, cortes, perspectivas y desarrollos.';const t=text.toLowerCase();if(t.includes('frontal')||t.includes('alzado'))r='La vista frontal o alzado conserva anchura y altura; la profundidad queda perpendicular al plano XY.';else if(t.includes('oculta'))r='Una arista oculta se representa con línea discontinua fina. Los ejes se distinguen mediante trazo y punto.';else if(t.includes('corte'))r='En Secciones y Cortes puedes elegir el tipo de corte, posición del plano, ángulo y separación del rayado.';else if(t.includes('desarrollo'))r='El desarrollo despliega las superficies del cuerpo. Puedes cambiar cuerpo, apertura y animar el proceso.';else if(t.includes('pista'))r=QUESTIONS[S.exercise].hint;S.messages.push({role:'assistant',text:r});S.recent.unshift('Consulta al asistente local');S.recent=S.recent.slice(0,8);save();render()}
function controlSelect(label,key,arr){return `<label class="field"><span>${label}</span><select onchange="setCfg('${key}',this.value)">${arr.map(v=>`<option value="${esc(v)}" ${String(S[key])===String(v)?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`}
function range(key,label,min,max,unit='',step='1'){return `<div class="range"><div class="rhead"><span>${label}</span><b>${esc(S[key])}${unit}</b></div><input type="range" min="${min}" max="${max}" step="${step}" value="${S[key]}" oninput="setCfg('${key}',this.value)"></div>`}
function controls(){let h=`<aside class="controls"><div class="section-title">CONTROL DE REPRESENTACIÓN</div><div class="control-label">CAPAS DEL DIBUJO</div>`;for(const k of Object.keys(S.flags))h+=`<label class="toggle"><span>${esc(k)}${k==='Ocultas'?' · · ·':''}</span><input type="checkbox" ${S.flags[k]?'checked':''} onchange="toggle('${esc(k)}')"></label>`;h+=controlSelect('Cámara 3D','camera',['Ortográfica','Perspectiva'])+`<div style="margin-top:12px">${controlSelect('Representación','render_mode',['Sólido + aristas','Sólido','Wireframe'])}</div>`;h+=`<div style="margin-top:13px"><span class="field"><span>MATERIAL</span><input type="color" value="${S.color}" onchange="setCfg('color',this.value)"></span></div>${range('light','Iluminación',1,5,'','0.1')}<div class="think">${icon('lightbulb')} <b>PIENSA EN EL ESPACIO</b><p>Una misma arista puede ser visible en el alzado y quedar oculta en la planta.</p></div><button class="assistant-link" onclick="navigate('Asistente IA local')">${icon('messages-square')} Consultar al asistente ↗</button><button class="btn" style="width:100%;margin-top:12px" onclick="resetView()">${icon('rotate-ccw')} Restablecer cámara</button></aside>`;return h}
function specificControls(){if(S.module==='Secciones y Cortes')return `<div class="control-label">PARÁMETROS DE CORTE</div>${controlSelect('Tipo de corte','cut_type',['Completa','Media','Parcial','Escalonada','Girada','Desplazada'])}${controlSelect('Rayado','hatch_style',['Simple','Cruzado'])}${range('cut','Posición del plano Y',-39,44,' mm')}${range('hatch_angle','Ángulo del rayado',0,90,'°')}${range('hatch_gap','Separación',4,20,' px')}<p class="muted-note">${cutHelp()}</p>`;if(S.module==='Perspectiva')return `<div class="control-label">PARÁMETROS DE PERSPECTIVA</div>${controlSelect('Sistema de representación','perspective',['Un punto','Dos puntos','Tres puntos','Caballera','Militar','Isométrica'])}<div class="grid3">${range('distance','Distancia',100,500)}${range('height','Altura',-40,80)}${range('orientation','Orientación',5,80,'°')}</div><p class="muted-note">Activa «Proyectantes» para prolongar las aristas. Los puntos fuera del campo se señalan en el borde.</p>`;if(S.module==='Desarrollo de Cuerpos')return `<div class="control-label">DESARROLLO</div>${controlSelect('Cuerpo desarrollable','body',['Prisma','Cilindro','Cono','Pirámide'])}${range('unfold','Apertura',0,100,'%')}<div class="actions"><button class="btn primary" onclick="playUnfold()">${S.unfolding?'Pausar':'Desplegar'}</button><button class="btn" onclick="resetUnfold()">Reiniciar</button></div><p class="muted-note">Prisma: bisagras sobre aristas. Cilindro: curvatura progresiva. Cono: interpolación didáctica hacia el sector.</p>`;if(S.module==='Proyecciones')return `<div class="control-label">PROYECCIÓN</div>${controlSelect('Método de proyección','projection',['Ortogonal','Oblicua','Isométrica','Dimétrica','Trimétrica'])}`;return ''}
function cutHelp(){return ({Completa:'Corte completo real mediante intersección horizontal de la geometría.',Media:'Media sección didáctica: conserva el plano completo sin dividir la mitad exterior.',Parcial:'Corte parcial didáctico: se muestra la sección horizontal completa.',Escalonada:'Corte escalonado aproximado mediante un tramo horizontal.',Girada:'Sección girada para facilitar la lectura en 2D.',Desplazada:'Contorno de sección separado del sólido con referencia A–A.'})[S.cut_type]}
function pieceBar(){return `<div class="piecebar"><div><div class="eyebrow">BIBLIOTECA DE PIEZAS</div><div class="selects" style="margin-top:7px">${controlSelect('Complejidad','level',['1','2','3','4','5','6'])}</div></div><div class="levels">${[1,2,3,4,5,6].map(n=>`<button class="level ${+S.level===n?'active':''}" onclick="setCfg('level','${n}')">${n}</button>`).join('')}</div><div class="piece-cards">${pieces().map(p=>`<button class="piece ${S.piece===p?'active':''}" title="${esc(PIECE_INFO[p][1])}" onclick="setCfg('piece','${esc(p)}')"><span class="picon">${PIECE_INFO[p][2]}</span><span><b>${esc(p)}</b><small>${esc(PIECE_INFO[p][0])}</small></span>${S.piece===p?icon('check'):''}</button>`).join('')}</div><div><div class="eyebrow">UNIDADES</div><span style="font-size:10px;color:#566b73">Milímetros · mm</span></div></div>`}
function drawing(id,title,subtitle,color){return `<div class="drawing"><div class="drawing-title"><i class="sq" style="background:${color}"></i>${title}<span class="sub">${subtitle}</span></div><svg id="${id}" viewBox="0 0 400 310"></svg></div>`}
function mainViews(){return `<div class="station-bar" style="display:flex;align-items:center;gap:8px;margin-bottom:10px">${icon('move-3d')}<span style="font-size:10px;font-weight:600;letter-spacing:.1em;color:#5f7c8a">ESTACIÓN DE VISTAS</span><select style="margin-left:auto;height:32px;border:1px solid #d4e0e7;border-radius:4px;padding:0 9px;color:#547686;font-size:11px" onchange="setCfg('view',this.value)">${['Frontal','Superior','Lateral','Posterior','Inferior','Isométrica','Axonométrica'].map(v=>`<option ${S.view===v?'selected':''}>${v}</option>`).join('')}</select><button class="mini" onclick="resetView()">${icon('rotate-ccw')}</button></div>${S.module==='Proyecciones'?`<div style="width:220px;margin-bottom:12px">${controlSelect('Método de proyección','projection',['Ortogonal','Oblicua','Isométrica','Dimétrica','Trimétrica'])}</div>`:''}<div class="view-grid"><div class="view-card"><div class="card-head">${icon('box')} OBJETO 3D <span class="tag">INTERACTIVO</span></div><div class="viewport" id="cad-viewport"><div class="viewport-label"><b>${esc(S.piece)}</b><span>MODELO PARAMÉTRICO</span></div><div class="viewport-tools"><button onclick="resetView()" title="Restablecer cámara">${icon('rotate-ccw')}</button><button onclick="setCfg('view','Isométrica')" title="Orientación isométrica">${icon('maximize')}</button></div><div class="axes"><span class="x">X</span><span class="y">Y</span><span class="z">Z</span></div></div><div class="viewport-note">${icon('mouse-pointer-2')} Toque: cara · Arrastrar: rotar · Rueda: zoom · Clic derecho: pan</div></div><div class="view-card"><div class="card-head">${icon('scan')} DIBUJO 2D <span class="tag">VINCULADO</span></div><div id="cad-main-view" style="height:350px;background:#fbfcfc"></div><div class="viewport-note">● Selecciona una arista para localizarla en 3D</div></div></div><div class="module-help">${icon('link')}<span id="cad-selection">Selecciona una cara 3D o una arista del dibujo</span><span style="margin-left:auto;font:9px monospace">2D ↔ 3D</span></div><div class="plane-legend"><div class="colors"><span class="al">■ Alzado · XY</span><span class="pl">■ Planta · XZ</span><span class="pe">■ Perfil · ZY</span></div><p>Toca una cara para seguirla del sólido a los tres planos.</p></div><div class="drawing-row">${drawing('cad-front','ALZADO','XY · FRONTAL','#D7654D')}${drawing('cad-top','PLANTA','XZ · SUPERIOR','#3478B8')}${drawing('cad-side','PERFIL','ZY · LATERAL','#3A8B68')}</div><div class="module-help">${icon('info')}<span>${esc(PIECE_INFO[S.piece][1])} Dimensiones en mm.</span></div>`}
function twin(){return `<div class="twin"><div><div class="view-card"><div class="card-head">${icon('box')} MODELO 3D · ${esc(S.piece)}</div><div class="viewport" id="cad-viewport"><div class="viewport-label"><b>${esc(S.piece)}</b><span>IDENTIFICACIÓN GEOMÉTRICA</span></div></div><div class="drawing-row" style="padding:8px;margin:0">${drawing('cad-front','ALZADO','XY','#D7654D')}${drawing('cad-top','PLANTA','XZ','#3478B8')}${drawing('cad-side','PERFIL','ZY','#3A8B68')}</div></div><div class="module-help">${icon('mouse-pointer-2')} Clic en una línea: arista. Clic en una superficie: cara. Arrastra para orbitar; rueda para zoom.</div></div><aside class="entity"><h3>IDENTIFICADORES GEOMÉTRICOS</h3><div id="cad-entity-list" class="entity-list">Los identificadores aparecerán al cargar la pieza.</div><div id="cad-entity-detail" class="entity-detail">Sin selección. Elige una arista o cara para consultar sus datos reales.</div></aside></div>`}
function special(){if(!['Fundamentos','Secciones y Cortes','Perspectiva','Desarrollo de Cuerpos'].includes(S.module))return '';return `<section class="special"><div class="special-head">${icon('drafting-compass')} ${esc(S.module)} <span style="margin-left:auto;font-size:9px;letter-spacing:.12em;color:#8b9fa8">MESA DE CONSTRUCCIÓN</span></div><div class="special-body">${S.module==='Secciones y Cortes'?specificControls():S.module==='Perspectiva'?specificControls():S.module==='Desarrollo de Cuerpos'?specificControls():'<p class="muted-note">Convenciones básicas de dibujo técnico · muestras esquemáticas. Usa las capas para comparar tipos de línea.</p>'}</div><div id="cad-special" class="special-canvas"></div></section>`}
function explanation(){if(!S.explaining)return '';return `<div class="explanation"><div class="exp-row"><div class="exp-text"><b>PASO ${S.step+1} DE 6</b><p>${STEPS[S.step]}</p></div><div class="exp-actions"><button class="mini" onclick="step(-1)">${icon('chevron-left')}</button><button class="mini" onclick="playExplain()">${S.playing?'Pausar':'Reproducir'}</button><button class="mini" onclick="step(1)">${icon('chevron-right')}</button></div></div><div class="progress6">${[0,1,2,3,4,5].map(i=>`<i class="${i<=S.step?'on':''}"></i>`).join('')}</div></div>`}
function exercisePanel(){const q=QUESTIONS[S.exercise];return `<section class="panel"><div class="eyebrow">ACTIVIDAD ${S.exercise+1} / 6 <span style="float:right">${S.score}/6 resueltas · ${S.attempts} intentos</span></div><h2>${q.question}</h2><div class="answers">${q.options.map((o,i)=>`<button class="answer ${S.answer===i?'selected':''}" onclick="answer(${i})"><b>${i+1}</b>${esc(o)}</button>`).join('')}</div>${S.checked?`<div class="feedback ${S.answer===q.answer?'ok':'bad'}">${S.answer===q.answer?'✓ Correcto.':'Revisa tu respuesta.'} ${esc(q.why)}</div>`:''}${S.hint_count?`<div class="hint">Pista: ${esc(S.hint_count===1?q.hint:q.why)}</div>`:''}<div class="actions"><button class="btn primary" onclick="check()">${icon('check')} Comprobar</button><button class="btn" onclick="hint()">${icon('lightbulb')} Pista ${S.hint_count}/2</button><button class="btn" onclick="nextEx()">Siguiente ${icon('arrow-right')}</button></div></section>`}
function examPanel(){if(S.exam_finished)return `<section class="panel"><div class="eyebrow">EVALUACIÓN FINAL</div><h2>Resultado: ${examScore()} / 5</h2><p>Revisa cada respuesta y vuelve a intentarlo cuando quieras.</p>${[1,2,3,4,5].map((qi,i)=>`<div class="review"><b>${esc(QUESTIONS[qi].question)}</b><span>${S.exam_answers[i]===QUESTIONS[qi].answer?'Correcta':'Por repasar'}</span></div>`).join('')}<div class="actions"><button class="btn primary" onclick="restartExam()">${icon('rotate-ccw')} Repetir evaluación</button></div></section>`;const q=QUESTIONS[[1,2,3,4,5][S.exam_index]];return `<section class="panel"><div class="eyebrow">EVALUACIÓN · ${S.exam_index+1} / 5</div><h2>${esc(q.question)}</h2><div class="answers">${q.options.map((o,i)=>`<button class="answer ${S.exam_answers[S.exam_index]===i?'selected':''}" onclick="examAnswer(${i})">${String.fromCharCode(65+i)} · ${esc(o)}</button>`).join('')}</div><div class="actions"><button class="btn primary" onclick="examNext()" ${S.exam_answers[S.exam_index]<0?'disabled':''}>${S.exam_index===4?'Finalizar evaluación':'Guardar y continuar'} ${icon('arrow-right')}</button></div></section>`}
function progressPanel(){return `<section class="panel"><div style="display:flex;align-items:center"><div><h2 style="margin:0">Tu recorrido, paso a paso</h2><p style="margin:3px 0">Solo esta sesión · no se guarda al reiniciar la aplicación.</p></div><strong style="margin-left:auto;font:500 34px 'Barlow Condensed';color:#427886">${S.score}/6</strong></div><div style="margin-top:13px">${MODULES.slice(0,8).map(m=>{const qs=QUESTIONS.filter(q=>q.module===m).length,sol=QUESTIONS.reduce((n,q,i)=>n+(q.module===m&&S.solved.includes(i)?1:0),0),v=qs?Math.round(sol/qs*100):(S.visited.includes(m)?25:0);return `<div class="progress-row"><div><b>${m}</b><span>${v}%</span></div><div class="bar"><i style="width:${v}%"></i></div><small style="font-size:9px;color:#93a8b2">${qs?`${sol}/${qs} actividades`:'Exploración (sin prueba de dominio)'}</small></div>`}).join('')}</div><div class="recent"><b>Actividad reciente</b>${S.recent.length?S.recent.map(x=>`<div>• ${esc(x)}</div>`).join(''):'<div>Tu actividad aparecerá aquí al explorar o resolver un ejercicio.</div>'}</div><div class="actions"><button class="btn" onclick="resetSession()">${icon('rotate-ccw')} Reiniciar progreso y conversación</button></div></section>`}
function chatPanel(){return `<section class="panel chat"><div class="eyebrow">ASISTENTE PEDAGÓGICO LOCAL</div><h2>${icon('messages-square')} Asistente pedagógico local <span style="float:right;font-size:9px">POR REGLAS</span></h2><p>Contexto activo: ${esc(S.piece)} · sin LLM, sin servicios externos de IA.</p><div class="messages">${S.messages.map(m=>`<div class="msg ${m.role}"><span>${m.role==='user'?'TÚ':'ASISTENTE LOCAL'}</span><p>${esc(m.text)}</p></div>`).join('')}</div><div class="actions" style="margin-bottom:12px"><button class="btn" onclick="reply('Explica la vista')">Explica la vista</button><button class="btn" onclick="reply('¿Qué es una oculta?')">¿Qué es una oculta?</button><button class="btn" onclick="reply('Dame una pista')">Dame una pista</button><button class="btn" onclick="reply('Explica el desarrollo')">Explica el desarrollo</button></div><div class="chat-form"><input id="chatInput" maxlength="600" placeholder="Pregunta sobre vistas, cotas, cortes…" onkeydown="if(event.key==='Enter'){event.preventDefault();reply(this.value);this.value=''}"><button onclick="const x=document.getElementById('chatInput');reply(x.value);x.value=''">${icon('send')}</button></div></section>`}
function modulePanel(){if(S.module==='Ejercicios')return exercisePanel();if(S.module==='Evaluación')return examPanel();if(S.module==='Progreso')return progressPanel();if(S.module==='Asistente IA local')return chatPanel();return ''}
function render(){sync();const nav=MODULES.map((m,i)=>`<button class="${S.module===m?'active':''}" onclick="navigate('${esc(m)}')">${icon(NAVICONS[i])}<span>${esc(m)}</span><small>${String(i+1).padStart(2,'0')}</small></button>`).join('');const isTwin=S.module==='Gemelo Geométrico 2D–3D';document.getElementById('app').innerHTML=`<header class="top"><div><div class="brand">ASISTENTE CAD</div><div class="sub">D I B U J O   T É C N I C O</div></div><div class="top-center"><span class="eyebrow" style="color:#a5bbc3">LABORATORIO</span><span>/</span><span style="font-size:12px">Geometría & representación</span></div><div class="top-right"><span>SESIÓN LOCAL</span><i class="dot"></i><span>Sin base de datos</span><span style="border:1px solid #566a72;padding:5px 7px">v1.0 HTML</span></div></header><div class="layout"><aside class="sidebar"><div class="side-head"><div class="eyebrow">ESPACIO DE APRENDIZAJE</div><div class="session"><i></i>Laboratorio personal</div></div><nav class="nav">${nav}</nav><div class="side-foot"><b>${icon('graduation-cap')} Aprender haciendo</b><div style="margin-top:6px">Explora el objeto. Construye la vista. Comprende el espacio.</div><div style="margin-top:12px;border-top:1px solid #dde4e6;padding-top:8px">SESIÓN LOCAL · protegida en este navegador</div></div></aside><main class="main">${pieceBar()}<div class="content"><div class="heading"><div><div class="crumb">LABORATORIO › EXPLORAR Y COMPRENDER</div><h1>${esc(S.module)}</h1><p>${esc(desc())}</p></div><button class="explain-btn" onclick="explain()">${icon('brain')} ${S.explaining?'CERRAR EXPLICACIÓN':'EXPLÍCAME'}</button></div>${explanation()}<div class="workspace"><div class="left-work">${isTwin?twin():mainViews()}${special()}${modulePanel()}${!isTwin?`<div class="legend"><span>━ Visible</span><span>┄ Oculta</span><span>━ Proyectante / selección</span><span style="margin-left:auto;color:#96a9b3">Visibilidad aproximada por normales; revisa las concavidades.</span></div>`:''}</div>${isTwin?'':controls()}</div></div></main></div><footer class="footer"><span id="cad-engine-status">Iniciando motor geométrico…</span><span>EDUCACIÓN TÉCNICA · ENTORNO EXPERIMENTAL · HTML LOCAL</span></footer>`;if(window.lucide)window.lucide.createIcons();save()}
load();render();
